// <auto-generated />
using System;
using AdfAgentMonitor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdfAgentMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314070000_AddAgentActivityLog")]
    partial class AddAgentActivityLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdfAgentMonitor.Core.Entities.AgentActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PipelineName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("PipelineRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResultMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AgentActivityLogs_Timestamp");

                    b.HasIndex("AgentName", "Timestamp")
                        .HasDatabaseName("IX_AgentActivityLogs_AgentName_Timestamp");

                    b.HasIndex("PipelineRunId")
                        .HasDatabaseName("IX_AgentActivityLogs_PipelineRunId");

                    b.ToTable("AgentActivityLogs", (string)null);
                });

            modelBuilder.Entity("AdfAgentMonitor.Core.Entities.PipelineRunState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovalStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DiagnosisCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DiagnosisSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("FactoryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PipelineName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PipelineRunId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RemediationPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemediationRisk")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TeamsMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId")
                        .IsUnique()
                        .HasDatabaseName("UX_PipelineRunStates_PipelineRunId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PipelineRunStates_Status");

                    b.HasIndex("FactoryName", "Status")
                        .HasDatabaseName("IX_PipelineRunStates_FactoryName_Status");

                    b.ToTable("PipelineRunStates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
